version: "3.7"

services:
    # image project
    app:
        container_name: teste-app
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - teste-app

    # nginx
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - teste-app

    # db postgres
    postgres:
        container_name: postgres
        image: postgres:14.5
        restart: unless-stopped
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/dbdata:/var/lib/postgresql/data
        ports:
            - "5488:5432"
        networks:
            - teste-app

    # # Node Service
    # node:
    #     image: node:alpine
    #     container_name: node
    #     restart: unless-stopped
    #     tty: true
    #     volumes:
    #         - ./:/var/www
    #     networks:
    #         - teste-app

    # redis
    redis:
        container_name: redis
        image: redis:latest
        networks:
            - teste-app

networks:
    teste-app:
        driver: bridge
